version: '3'
services:
        trino:
                image: trinodb/trino:latest
                ports:
                        - 9090:8080
                volumes:
                  - ./target/etc:/etc/trino
